version: '3.8'

services:
  whisper-api:
    build: .
    ports:
      - "8090:8080"
    environment:
      - FLASK_ENV=production
    volumes:
      - whisper-models:/opt/whisper.cpp/models
      - ./logs:/var/log/whisper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '3.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "90:80"
      - "4443:443"
    depends_on:
      - whisper-api
    restart: unless-stopped 
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  whisper-models: