#!/bin/bash

echo "🎤 Whisper Service - Scripts Disponibles"
echo "========================================"
echo ""

echo "🚀 DÉMARRAGE"
echo "  npm start          - Démarrage automatique complet"
echo "  npm run dev        - Mode développement (sans Docker)"
echo "  npm run setup      - Installation et démarrage complet"
echo "  npm run reset      - Reset complet (nettoyage + redémarrage)"
echo ""

echo "🐳 DOCKER"
echo "  npm run build      - Construire l'image Docker"
echo "  npm run up         - Démarrer les services"
echo "  npm run down       - Arrêter les services"
echo "  npm run restart    - Redémarrer les services"
echo "  npm run status     - Statut des conteneurs"
echo "  npm run clean      - Nettoyer Docker (volumes + images)"
echo ""

echo "🧪 TESTS"
echo "  npm test           - Tests complets de l'API"
echo "  npm run test-local - Test simple avec fichier local"
echo "  npm run test-health- Test du health check"
echo "  npm run test-models- Lister les modèles"
echo "  npm run test-transcribe - Test de transcription"
echo "  npm run benchmark  - Test de performance"
echo ""

echo "📊 MONITORING"
echo "  npm run logs       - Logs du service Whisper"
echo "  npm run logs-all   - Logs de tous les services"
echo "  npm run monitor    - Monitoring des ressources Docker"
echo "  npm run shell      - Accès shell au conteneur"
echo ""

echo "🔧 MAINTENANCE"
echo "  npm run install-deps    - Installer dépendances Python"
echo "  npm run install-whisper - Installer Whisper.cpp manuellement"
echo "  npm run download-models - Télécharger les modèles"
echo "  npm run backup-models   - Sauvegarder les modèles"
echo "  npm run restore-models  - Restaurer les modèles"
echo "  npm run nginx-reload    - Recharger Nginx"
echo ""

echo "🚀 DÉPLOIEMENT"
echo "  npm run deploy-railway  - Instructions Railway"
echo "  npm run deploy-render   - Instructions Render"
echo ""

echo "❓ AIDE"
echo "  npm run help       - Afficher cette aide"
echo ""

echo "💡 EXEMPLES D'UTILISATION"
echo "  # Démarrage rapide"
echo "  npm start"
echo ""
echo "  # Test avec votre fichier audio"
echo "  npm run test-local"
echo ""
echo "  # Voir les logs en temps réel"
echo "  npm run logs"
echo ""
echo "  # Nettoyer et redémarrer"
echo "  npm run reset" 